const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const seedTsPath = path.join(__dirname, '../data/chennai-stations-seed.ts');
if (!fs.existsSync(seedTsPath)) {
  console.error(`Seed file not found at ${seedTsPath}`);
  process.exit(1);
}

// 1. Read existing seed file and convert to CommonJS in memory
let seedContent = fs.readFileSync(seedTsPath, 'utf8');

// Strip interface and export const to make it plain commonjs module
const stripped = seedContent
  .replace(/export interface[\s\S]*?\n\}/, '')
  .replace(': ChennaiStation[]', '')
  .replace('export const CHENNAI_POLICE_STATIONS =', 'module.exports =');

const tempJsPath = path.join(__dirname, './temp_seed_tondiarpet.js');
fs.writeFileSync(tempJsPath, stripped, 'utf8');
const CHENNAI_POLICE_STATIONS = require(tempJsPath);
fs.unlinkSync(tempJsPath);

// 2. Find and update Tondiarpet (id: 6)
const tondiarpet = CHENNAI_POLICE_STATIONS.find(s => s.id === 6);
if (tondiarpet) {
  tondiarpet.station_image = "/images/toun.png";
  console.log(`Updated Tondiarpet Police Station (id: 6) station_image to ${tondiarpet.station_image}`);
} else {
  console.error("Could not find Tondiarpet Police Station (id: 6) in seed list!");
  process.exit(1);
}

// 3. Write back to TS seed file
const newSeedContent = `/**
 * Chennai Police Stations - Aligned & Expanded Dataset
 * Automatically generated by update_tondiarpet_image.js
 */

export interface ChennaiStation {
  id: number;
  station_name: string;
  station_code: string;
  area_name: string;
  locality: string;
  zone: string;
  division: string;
  category: string;
  type: string;
  address_en: string;
  landmark: string;
  pincode: string;
  phone: string;
  alternate_phone: string;
  email: string;
  lat: number;
  lng: number;
  jurisdiction_areas: string;
  working_hours: string;
  is_active: number;
  station_image?: string;
}

export const CHENNAI_POLICE_STATIONS: ChennaiStation[] = ${JSON.stringify(CHENNAI_POLICE_STATIONS, null, 2)};
`;

fs.writeFileSync(seedTsPath, newSeedContent, 'utf8');
console.log(`Successfully rewrote ${seedTsPath}.`);

// 4. Re-run the seeding script to update the MySQL database
console.log("Re-seeding database...");
try {
  const result = execSync('node src/scripts/seed_police_stations.js', { encoding: 'utf8' });
  console.log(result);
  console.log("Database seeded successfully!");
} catch (err) {
  console.error("Seeding database failed:", err.message);
  process.exit(1);
}
